// p8 popup layout: geometry (targets, dead bands, wrapping, AA) for 4 content cases x 5 cities, + before/after stills at 3x (~4x) and 1x.
const L = require('./lib'); const fs = require('fs');
const CASES = [['bare: no address/notes, unvisited, unstarred', 0, {}], ['address + notes, visited, starred, long name', 1, { address: 'Sibyllegatan 2, 114 51 Stockholm', notes: 'Book the 11:00 tour; café on the top floor closes at 16.' }],
  ['notes only, unvisited, starred', 0, { notes: 'Cardamom bun, go early.', starred: true }], ['address only, visited', 7, { address: 'Hans Michelsensgatan 3, Malmö', visited: true }],
  ['title wraps, no address, starred', 3, { name: 'Hallgrímskirkja church tower and the Leifur Eiríksson statue', address: null, notes: null, starred: true }], ['title wraps + address, unstarred', 4, { name: 'Harpa Concert Hall and Conference Centre, Reykjavík harbour', address: 'Austurbakki 2, 101 Reykjavík', notes: null, starred: false }]];
async function openPop(page, i, patch) { return page.evaluate(async ([i, patch]) => { Object.assign(locations[i], patch); const loc = locations[i]; updateUI(); map.setView([loc.lat, loc.lng], 16, { animate: false }); await new Promise(r => setTimeout(r, 150)); updateUI();
  markersById.get(loc.id).marker.openPopup(); await new Promise(r => setTimeout(r, 350)); const w = document.querySelector('.leaflet-popup-content-wrapper').getBoundingClientRect(); return { x: w.x - 6, y: w.y - 6, width: w.width + 12, height: w.height + 30 }; }, [i, patch]); }
(async () => { const b = await L.launch(); const geo = {};
  for (const city of ['stockholm', 'reykjavik', 'copenhagen', 'malmo', 'oslo']) { let o; try { o = await L.openProto(b, { dsf: 1, file: L.FILE, city }); } catch (e) { continue; }
    const { ctx, page } = o;
    for (const [label, i, patch] of CASES) { await openPop(page, i, patch);
      geo[city + ' | ' + label] = await page.evaluate(() => { const q = s => document.querySelector('.leaflet-popup ' + s); const R = e => e.getBoundingClientRect();
        const w = R(q('.leaflet-popup-content-wrapper')), star = q('.popup-star'), sr = R(star), a = getComputedStyle(star, '::after'); const ins = ['top', 'right', 'bottom', 'left'].map(k => parseFloat(a[k]));
        const sh = { top: sr.top + ins[0], bottom: sr.bottom - ins[2], left: sr.left + ins[3], right: sr.right - ins[1] }; const tap = R(q('.popup-star-tap'));
        const dir = q('.popup-directions'), dr = R(dir), da = getComputedStyle(dir, '::after'); const hasAfter = da.content !== 'none' && da.position === 'absolute'; const dh = hasAfter ? { top: dr.top + parseFloat(da.top), bottom: dr.bottom - parseFloat(da.bottom) } : { top: dr.top, bottom: dr.bottom }; const vtap = q('.popup-visited-tap'), vt = vtap ? R(vtap) : null;
        const vis = q('.popup-visited'), vr = R(vis), cat = q('.popup-cat'), cr = R(cat);
        const lum = c => { const n = c.match(/[\d.]+/g).map(Number); const rgb = c.startsWith('color(srgb') ? n.slice(0, 3) : n.slice(0, 3).map(x => x / 255); const Lc = rgb.map(x => x <= 0.04045 ? x / 12.92 : Math.pow((x + 0.055) / 1.055, 2.4)); return 0.2126 * Lc[0] + 0.7152 * Lc[1] + 0.0722 * Lc[2]; };
        const cr_ = (f, g) => { const a2 = lum(f), b2 = lum(g); return +((Math.max(a2, b2) + 0.05) / (Math.min(a2, b2) + 0.05)).toFixed(2); };
        const bg = getComputedStyle(q('.leaflet-popup-content-wrapper')).backgroundColor;
        const hit = (x, y) => { const e = document.elementFromPoint(x, y); return e ? String((e.closest('.popup-star-tap, .popup-visited-tap, .popup-directions, .popup-visited, .popup-title, .popup-cat') || e).className.baseVal ?? (e.closest('.popup-star-tap, .popup-visited-tap, .popup-directions, .popup-visited, .popup-title, .popup-cat') || e).className).split(' ')[0] || e.tagName : null; };
        return { popupW: Math.round(w.width), starTargetH: Math.round(sh.bottom - sh.top), starTargetTopVsPopup: +(sh.top - w.top).toFixed(1), tapMatches: Math.abs(tap.top - sh.top) < 0.5 && Math.abs(tap.height - (sh.bottom - sh.top)) < 0.5,
          deadStarToDir: +(dh.top - sh.bottom).toFixed(1), dirTargetH: Math.round(dh.bottom - dh.top), deadDirToVisited: +(vr.top - dh.bottom).toFixed(1), visitedH: Math.round(vr.height),
          visitedOneLine: (() => { const rg = document.createRange(); rg.selectNodeContents(vis.firstChild); return new Set([...rg.getClientRects()].map(r => Math.round(r.top))).size === 1; })(), contentW: Math.round(q('.leaflet-popup-content').getBoundingClientRect().width),
          star: (() => { const t = R(q('.popup-title')), tl = q('.popup-title'); const rg = document.createRange(); rg.setStart(tl.firstChild, 0); rg.setEnd(tl.firstChild, 1); const l1 = rg.getClientRects()[0]; const nxt = q('.popup-addr'); const lines = new Set([...(() => { const r2 = document.createRange(); r2.selectNodeContents(tl); return r2.getClientRects(); })()].map(r => Math.round(r.top))).size; const blockBottom = nxt ? R(nxt).bottom : t.bottom; return { size: Math.round(sr.width) + 'x' + Math.round(sr.height), gapToTitle: +(t.left - sr.right).toFixed(2), indent: +(t.left - R(q('.leaflet-popup-content')).left).toFixed(2), titleLines: lines, centreVsBlock: +((sr.top + sr.bottom) / 2 - (t.top + blockBottom) / 2).toFixed(2) }; })(), catClipped: cat.scrollWidth > cat.clientWidth + 0.5, visitedRightInset: +(w.right - vr.right).toFixed(1), checkRightOfLabel: R(q('.popup-visited-check')).left > vr.left + 20,
          dirOneLine: (() => { const rg = document.createRange(); rg.selectNodeContents(dir); return new Set([...rg.getClientRects()].filter(r => r.width > 0).map(r => Math.round(r.top + r.height / 2))).size === 1; })(), dirW: Math.round(dr.width), dirTextLeft: +((() => { const rg = document.createRange(); rg.selectNodeContents(dir.lastChild); return rg.getBoundingClientRect().left; })() - R(q('.leaflet-popup-content')).left).toFixed(2), catWordLeft: +((() => { const rg = document.createRange(); rg.selectNodeContents(cat.lastChild); return rg.getBoundingClientRect().left; })() - R(q('.leaflet-popup-content')).left).toFixed(2), vTapMatches: !!vt && Math.abs(vt.top - vr.top) < 0.5 && Math.abs(vt.left - vr.left) < 0.5 && Math.abs(vt.width - vr.width) < 0.5 && Math.abs(vt.height - vr.height) < 0.5, dirHasBg: getComputedStyle(dir).backgroundColor !== 'rgba(0, 0, 0, 0)', dirColor: getComputedStyle(dir).color,
          aa: { dirText: cr_(getComputedStyle(dir).color, getComputedStyle(dir).backgroundColor === 'rgba(0, 0, 0, 0)' ? bg : getComputedStyle(dir).backgroundColor), visitedText: cr_(getComputedStyle(vis).color, bg), catText: cr_(getComputedStyle(cat).color, bg) },
          hits: { starCorner: hit(sh.left + 2, sh.top + 2), starBottom: hit((sh.left + sh.right) / 2, sh.bottom - 2), deadBand: hit((sh.left + sh.right) / 2, sh.bottom + 4), dirEdge: hit(dr.left + 20, dh.top + 1), visitedTop: hit(vr.left + vr.width / 2, vr.top + 2), rightOfDir: hit(dr.right + 6, (dh.top + dh.bottom) / 2) },
          names: { star: star.getAttribute('aria-label') + '/' + star.getAttribute('aria-pressed'), visited: vis.textContent.trim() + '/' + vis.getAttribute('aria-pressed'), dir: dir.getAttribute('aria-label') } }; });
      await page.evaluate(() => map.closePopup()); }
    await ctx.close(); }
  fs.writeFileSync(L.outPath('popup-geo-cases.json'), JSON.stringify(geo, null, 1));
  // stills: before (main) / after (p8), 4 cases, 3x (~4x shown) and 1x
  const shots = [];
  for (const dsf of [3, 1]) for (const [tag, file] of [['before (main)', L.BASE_FILE], ['after (proto)', L.FILE]]) { const { ctx, page } = await L.openProto(b, { dsf, file });
    for (const [label, i, patch] of CASES) { const clip = await openPop(page, i, patch); shots.push([dsf, tag, label, (await page.screenshot({ clip })).toString('base64'), clip.width]); await page.evaluate(() => map.closePopup()); }
    await ctx.close(); }
  const p = await b.newPage();
  await p.setContent(`<body style="margin:0;padding:10px;font:600 12px system-ui;background:#fff"><h3>Popup layout — before (main) / after (p8 revised: Get Directions back to the shipped text button, under the notes). Stockholm. Top: 3x shown ~4x; bottom: 1x shown 2x (nearest-neighbour).</h3>` +
    [3, 1].map(dsf => `<div style="display:grid;grid-template-columns:repeat(6,max-content);gap:8px 14px;margin:8px 0">` + shots.filter(s => s[0] === dsf).map(([d, tag, label, data, w]) => `<div><div style="max-width:${Math.round(w * (d === 3 ? 4 / 3 : 2))}px">${tag}<br><span style="font-weight:400">${label}</span></div><img style="image-rendering:${d === 1 ? 'pixelated' : 'auto'};width:${Math.round(w * (d === 3 ? 4 / 3 : 2))}px;outline:1px solid #ccc" src="data:image/png;base64,${data}"></div>`).join('') + '</div>').join(''));
  await p.waitForTimeout(300); await p.screenshot({ path: L.outPath('popup-geo.png'), fullPage: true });
  const g = Object.values(geo); console.log(JSON.stringify({ cases: g.length, minDeadStarToDir: Math.min(...g.map(x => x.deadStarToDir)), minDeadDirToVisited: Math.min(...g.map(x => x.deadDirToVisited)), starTargetH: [...new Set(g.map(x => x.starTargetH))], starTopVsPopup: Math.min(...g.map(x => x.starTargetTopVsPopup)), contentW: [Math.min(...g.map(x => x.contentW)), Math.max(...g.map(x => x.contentW))], starCentreOff: [Math.min(...g.map(x => x.star.centreVsBlock)), Math.max(...g.map(x => x.star.centreVsBlock))], gap: [...new Set(g.map(x => x.star.gapToTitle))], indent: [...new Set(g.map(x => x.star.indent))], hitsBad: g.filter(x => x.hits.starCorner !== 'popup-star-tap' || x.hits.starBottom !== 'popup-star-tap' || x.hits.dirEdge !== 'popup-directions' || x.hits.visitedTop !== 'popup-visited-tap').length, dirTargetH: [...new Set(g.map(x => x.dirTargetH))], visitedH: [...new Set(g.map(x => x.visitedH))], allOneLine: g.every(x => x.visitedOneLine), dirOneLine: g.every(x => x.dirOneLine), vTapMatches: g.every(x => x.vTapMatches), dirHasBg: g.some(x => x.dirHasBg), dirColor: [...new Set(g.map(x => x.dirColor))], dirW: [...new Set(g.map(x => x.dirW))], dirTextLeft: [...new Set(g.map(x => x.dirTextLeft))], catWordLeft: [...new Set(g.map(x => x.catWordLeft))], rightOfDir: [...new Set(g.map(x => x.hits.rightOfDir))], anyCatClipped: g.some(x => x.catClipped), widths: [Math.min(...g.map(x => x.popupW)), Math.max(...g.map(x => x.popupW))], minAA: { dir: Math.min(...g.map(x => x.aa.dirText)), visited: Math.min(...g.map(x => x.aa.visitedText)), cat: Math.min(...g.map(x => x.aa.catText)) }, tapMatches: g.every(x => x.tapMatches), checkRight: g.every(x => x.checkRightOfLabel), hits: [...new Set(g.map(x => JSON.stringify(x.hits)))], names: g[1].names }, null, 1));
  const okG = g.length === 24 && g.every(x => x.deadStarToDir >= 8 && x.deadDirToVisited >= 8 && x.starTargetH === 44 && x.starTargetTopVsPopup >= 0 && x.hits.starCorner === 'popup-star-tap' && x.hits.starBottom === 'popup-star-tap' && x.hits.dirEdge === 'popup-directions' && x.hits.visitedTop === 'popup-visited-tap' && x.visitedOneLine && x.dirOneLine && x.vTapMatches && x.tapMatches && x.checkRightOfLabel && !x.catClipped && !x.dirHasBg && x.star.centreVsBlock === 0 && Math.min(x.aa.dirText, x.aa.visitedText, x.aa.catText) >= 4.5);
  console.log(okG ? 'ALL PASS' : 'FAIL (see popup-geo-cases.json)');
  await b.close(); process.exitCode = okG ? 0 : 1; })();
